### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Bjornskjald** [ChatPlug/libfb-js#2]
**1.0.0**: Basic API
- [x] Send messages
- [x] Receive messages
- [x] Receive events
- [x] Get user info
- [x] Get thread info

**1.1.0**:
- [x] Get thread list

**1.2.0**:
- [ ] Save session
- [ ] Load session
